version : "3.8"
services:
  database:
    image: "mariadb"
    container_name : "mariadb-container"
    volumes:
      - ../data:/data
      - ../mariadb/conf.d:/etc/mysql/conf.d
      - ../mariadb/bubbleMyTea:/var/lib/mysql
    ports:
      - "9906:3306"
    environment:
      MYSQL_DATABASE: bubbleMyTea
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: bubbleMyTea_user
      MYSQL_PASSWORD :